#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod "saz/vim"

mod 'theforeman-git'

mod 'puppetlabs-ruby'
mod "puppetlabs/apt"
mod "puppetlabs/stdlib"

mod "elasticsearch/elasticsearch"
mod "elasticsearch/logstash"
mod "tylerwalts/jdk_oracle"
