#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod "saz/vim"

mod 'theforeman-git'

mod 'puppetlabs-ruby'
mod "puppetlabs/apt"
mod "puppetlabs/stdlib"
mod "puppetlabs/java"

mod "elastic/elasticsearch"
mod "elastic/logstash"
