# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  VM_IP = "172.17.1.22".freeze

  config.landrush.enabled = true
  config.landrush.host 'elastic.dev', VM_IP
  config.landrush.tld = 'dev'

  config.vm.box = "puphpet/ubuntu1404-x64"
  config.vm.hostname = "elasticsearch.dev"
  config.vm.network "private_network", ip: VM_IP

  config.ssh.forward_agent = true

  config.vm.synced_folder "..", "/vagrant", type: 'nfs'

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path    = ["modules", "custom_modules"]
  end

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end
end
