# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  VM_IP = "172.17.1.22".freeze

  config.landrush.enabled = true
  config.landrush.host 'elastic.dev', VM_IP
  config.landrush.tld = 'dev'

  config.ssh.forward_agent = true

  config.vm.synced_folder "..", "/vagrant"

  config.vm.define "elasticsearch-ubuntu" do |box|
    box.vm.box = "puphpet/ubuntu1404-x64"
    box.vm.hostname = "elastic.dev"
    box.vm.network "private_network", ip: VM_IP
  end

  config.vm.provision :puppet do |puppet|
    puppet.module_path       = ["modules", "custom_modules"]
    puppet.environment       = 'development'
    puppet.environment_path  = 'env'
    puppet.options           = ['--verbose', '--debug']
  end

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end
end
